icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#458588"
info_fg = "#ebdbb2"
good_bg = "#98971a"
good_fg = "#ebdbb2"
warning_bg = "#d79921"
warning_fg = "#ebdbb2"
critical_bg = "#cc241d"
critical_fg = "#ebdbb2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %I:%M %p') "

[[block]]
block = "battery"
interval = 10

# Normal display
format = " $icon $percentage $time "

# Charging display
charging_format = " $bat_charging "

# Full / Empty
full_format = " $icon Full "
empty_format = " $icon Empty "

# Thresholds (will pick up your theme's good/warning/critical colors)
good = 80
warning = 20
critical = 10
